apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainstats-ui
  labels:
    app: trainstats-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainstats-ui
  template:
    metadata:
      labels:
        app: trainstats-ui
    spec:
      containers:
        - name: trainstats-ui
          image: registry.digitalocean.com/mat-n-image-registry/trainstats-ui@sha256:5e6ead04e4c2f91387d8d1b75cb9de7f6d7063b7a09963d980edc1ab56346ba3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trainstats-ui
spec:
  selector:
    app: trainstats-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
