apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainstats-ui
  labels:
    app: trainstats-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainstats-ui
  template:
    metadata:
      labels:
        app: trainstats-ui
    spec:
      containers:
        - name: trainstats-ui
          image: registry.digitalocean.com/matnicholls/trainstats-ui@sha256:18c4af219acb0338681521527e00e8bfde66e6caf0ca9b8548c3beb20a26e69e
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trainstats-ui
spec:
  selector:
    app: trainstats-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
