apiVersion: apps/v1
kind: Deployment
metadata:
  name: trainstats-realtime
  labels:
    app: trainstats-realtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trainstats-realtime
  template:
    metadata:
      labels:
        app: trainstats-realtime
    spec:
      containers:
        - name: trainstats-realtime
          image: registry.digitalocean.com/mat-n-image-registry/trainstats-realtime@sha256:8e3e9f306f92089589536078313475808d48a10cd24607f698818ef0d7cf461b
          env:
            - name: NR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: nr-credentials
                  key: nr-username
            - name: NR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nr-credentials
                  key: nr-password
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: trainstats-realtime
  namespace: default
spec:
  selector:
    app: trainstats-realtime
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP